USE [PIZZA]
GO

/****** Object:  Table [dbo].[CLIENT]    Script Date: 20/12/2018 11:23:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CLIENT](
	[N°Client] [int] NOT NULL,
	[NomClient] [nchar](10) NOT NULL,
	[Adresse] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_CLIENT] PRIMARY KEY CLUSTERED 
(
	[N°Client] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

